---
- name: install nginx
  yum: name=nginx state=latest

- name: replace index.html
  template: src=index.html.j2 dest=/usr/share/nginx/html/index.html

- name: nginx start
  service: name=nginx state=started enabled=yes